Sam/upgrades and fixes
EdgeApp/edge-sync-server pull request #25
Opened 2021-01-07 21:31 UTC by samholmes

Includes upgrade for eslint-config-standard-kit with the necessary lint error fixes. Also, includes fixes for other issues.

2021-01-12 19:55 UTC, paullinator approved these changes

2021-01-12 19:57 UTC, paullinator requested changes
n/a

2021-01-13 21:34 UTC, samholmes commented on src/api/updateFiles.ts
> +  return await withRetries(
Return withRetries directly (remove async/await and return)

2021-01-13 21:34 UTC, samholmes commented on test/utils.ts
> +    ].join(' ')
Try using `JSON.stringify()` or `String()` to make ESLint happy.

2021-01-18 20:01 UTC, thehobbit85 approved these changes

2021-01-18 20:03 UTC, merged